# Generated by Django 4.0.1 on 2022-01-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
