# Generated by Django 4.0.1 on 2022-02-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('hostel_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=20)),
                ('end_date', models.DateField(max_length=20)),
                ('total_paid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
