# Generated by Django 4.0.1 on 2022-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
