# Generated by Django 4.0 on 2022-01-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_username',
            new_name='username',
        ),
    ]
