# Generated by Django 4.0 on 2022-01-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=100)),
                ('customername', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=20)),
                ('hostel_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hostel',
            },
        ),
    ]
