# Generated by Django 4.0 on 2022-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(default='admin', max_length=100)),
                ('email', models.CharField(default='admin@gmail.com', max_length=100, unique=True)),
                ('password', models.CharField(default='admin', max_length=8)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
